#application.yml配置文件
server:
  port: 8086 # 端口号
  servlet:
    context-path: /hello # 上下文路径
#数据源配置
spring:
  application:
    name: hellospringboot
    charset: utf-8 # 字符编码
  datasource:
    url: jdbc:mysql://localhost:3306/myyunmengfayuan?useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true #rewriteBatchedStatements=true 设置mysql开启批处理
    username: root
    password: H3u94c94kod0UjGuNmkfmqw0JMJRMF
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #数据源其他配置
    # Druid连接池配置
    druid:
      # 初始化大小
      initial-size: 5
      # 最小连接数
      min-idle: 5
      # 最大连接数
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 检测间隔时间
      time-between-eviction-runs-millis: 60000
      # 连接最小生存时间
      min-evictable-idle-time-millis: 300000
      # 验证查询
      validationQuery: SELECT 1 FROM DUAL
      # 申请连接时执行validationQuery检测连接是否有效
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效
      test-on-return: false
      # 空闲时检测
      test-while-idle: true
      # 配置监控统计拦截的filters
      filters: stat,wall,slf4j
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      schema: classpath:static/add.sql #初始化时运行脚本
      initialize-schema: always # 初始化数据库schema
      # WebStatFilter配置
      web-stat-filter: # WebStatFilter配置 关联Druid的监控信息
        enabled: true # 是否启用WebStatFilter
        url-pattern: /* # 监控页面URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      # StatViewServlet配置（druid链接监控）
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/* # 监控页面URL
        reset-enable: false
        login-username: admin # 登录用户名
        login-password: admin # 登录密码
        allow: 127.0.0.1  # 允许访问的IP地址
        deny: 192.168.1.100 # 拒绝访问的IP地址
